name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build backend Docker image
      run: docker build -t graphql-backend:latest -f graphql-server/Dockerfile ./graphql-server

    - name: Build frontend Docker image
      run: docker build -t graphql-frontend:latest -f graphql-client/Dockerfile ./graphql-client

    - name: Stop and remove existing containers
      run: |
        docker stop graphql-backend || true
        docker rm graphql-backend || true
        docker stop graphql-frontend || true
        docker rm graphql-frontend || true

    - name: Run backend container
      run: |
        docker run -d --name graphql-backend -p 4000:4000 graphql-backend:latest

    - name: Run frontend container
      run: |
        docker run -d --name graphql-frontend -p 80:80 graphql-frontend:latest
